// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfyUKciZxPVjZYMprq-wiRVruQ4jHBICE',
    appId: '1:383649791178:web:8fb255dc9bc3187f3e8833',
    messagingSenderId: '383649791178',
    projectId: 'samp-app-back',
    authDomain: 'samp-app-back.firebaseapp.com',
    storageBucket: 'samp-app-back.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAK_cp6UQaMVF0njFoWp0_4ajIZOqvY7s',
    appId: '1:383649791178:android:1f14511dd2353d203e8833',
    messagingSenderId: '383649791178',
    projectId: 'samp-app-back',
    storageBucket: 'samp-app-back.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCUCIdFeaGcPN6QBZIV1wofOEU40LYA8',
    appId: '1:383649791178:ios:734f7e7a26b926303e8833',
    messagingSenderId: '383649791178',
    projectId: 'samp-app-back',
    storageBucket: 'samp-app-back.firebasestorage.app',
    iosBundleId: 'com.example.sam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoCUCIdFeaGcPN6QBZIV1wofOEU40LYA8',
    appId: '1:383649791178:ios:734f7e7a26b926303e8833',
    messagingSenderId: '383649791178',
    projectId: 'samp-app-back',
    storageBucket: 'samp-app-back.firebasestorage.app',
    iosBundleId: 'com.example.sam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfyUKciZxPVjZYMprq-wiRVruQ4jHBICE',
    appId: '1:383649791178:web:77d693993d2453533e8833',
    messagingSenderId: '383649791178',
    projectId: 'samp-app-back',
    authDomain: 'samp-app-back.firebaseapp.com',
    storageBucket: 'samp-app-back.firebasestorage.app',
  );
}
